version: "2.1"

services:
  db:
    restart: "always"
    image: "bitnami/mysql:latest"
    ports:
      - "3309:3306"
    volumes:
      - "/srv/deploy/db:/bitnami/mysql/data"
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=America/Fortaleza
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mysql/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6
