@host = http://localhost:5000

### Rota para criar um profile
POST {{host}}/profiles
Content-Type: application/json

{
  "description": "null",
  "equips_id": null,
  "read_write": false
}

### List
GET {{host}}/profiles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTYyNzExMTIsImV4cCI6MTYxNjM1NzUxMiwic3ViIjoie1wiaWRcIjoxLFwib2x0c19pZFwiOm51bGwsXCJyZWFkX3dyaXRlXCI6Mn0ifQ.ojPbZx3uOENtiWG6OJ6zw0uLmSVW-pKdFindVFqNAqM

### Update dos Profiles
PUT {{host}}/profiles/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTYyNzExMTIsImV4cCI6MTYxNjM1NzUxMiwic3ViIjoie1wiaWRcIjoxLFwib2x0c19pZFwiOm51bGwsXCJyZWFkX3dyaXRlXCI6Mn0ifQ.ojPbZx3uOENtiWG6OJ6zw0uLmSVW-pKdFindVFqNAqM

{
  "equips_id": []
}

### Delete Profiles
DELETE {{host}}/profiles/6